# Si tu sitio está en un subdirectorio (por ejemplo, https://tu-usuario.github.io/tu-repo/)
# establece baseurl a /tu-repo/ (con la barra final)
# Si tu sitio está en la raíz (por ejemplo, https://tu-usuario.github.io/)
# deja baseurl en blanco o /.
baseurl: ""

source: src

# Excluir archivos o carpetas que no deben ser copiados al sitio generado
exclude:
  - README.md
  - LICENSE
  - .git/

# Incluir archivos o carpetas que deben ser copiados al sitio generado
include:
  - data/
  - assets/

