name: Sync Notion Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (optional, if you use a script)
        run: npm install axios

      - name: Fetch Notion data and generate JSON
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DATABASE_ID: "26d99f27fb17806fb29fe696ad0e4043"
        run: |
          mkdir -p data
          NODE_OPTIONS='--experimental-fetch' node -e ' 
            const axios = require("axios");
            async function fetchServices() {
              try {
                const databaseId = process.env.NOTION_DATABASE_ID;

                // Llamada directa a la API REST de Notion usando axios
                const response = await axios.post(
                  `https://api.notion.com/v1/databases/${databaseId}/query`,
                  {
                    sorts: [
                      {
                        property: "Nombre del Servicio", 
                        direction: "ascending",
                      },
                    ],
                  },
                  {
                    headers: {
                      Authorization: `Bearer ${process.env.NOTION_API_TOKEN}`,
                      "Notion-Version": "2022-06-28",
                      "Content-Type": "application/json",
                    },
                  }
                );

                const services = response.data.results.map(page => ({
                  title: page.properties["Nombre del Servicio"].title[0].plain_text, 
                  description: page.properties.Descripción.rich_text[0].plain_text, 
                  // Añade más propiedades según la estructura de tu tabla de Notion
                }));
                require("fs").writeFileSync("data/services.json", JSON.stringify(services, null, 2));
                console.log("services.json generated successfully.");
              } catch (error) {
                console.error("Error fetching Notion data:", error);
                // Escribir un array vacío para prevenir fallos en el despliegue
                require("fs").writeFileSync("data/services.json", JSON.stringify([], null, 2));
                console.log("Generated empty services.json due to error.");
              }
            }
            fetchServices();
          '
      - name: Upload _data directory
        uses: actions/upload-artifact@v4
        with:
          name: notion-data
          path: data

  build:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Notion data
        uses: actions/download-artifact@v4
        with:
          name: notion-data
          path: data

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: . # Tu sitio de Jekyll está en la raíz
          destination: _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
