name: Sync Notion Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (optional, if you use a script)
        run: npm install axios

      - name: Install Notion client
        run: npm install @notionhq/client@latest

      - name: Fetch Notion data and generate JSON
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DATABASE_ID: "26d99f27fb17806fb29fe696ad0e4043"
        run: |
          mkdir -p _data
          NODE_OPTIONS='--experimental-fetch' node -e ' 
            const { Client } = require("@notionhq/client");
            const notion = new Client({ auth: process.env.NOTION_API_TOKEN });
            async function fetchServices() {
              console.log("Notion client object:", notion);
              console.log("Notion databases object:", notion.databases);
              try {
                const databaseId = process.env.NOTION_DATABASE_ID;
                const response = await notion.databases.query({
                  database_id: databaseId,
                  sorts: [
                    {
                      property: "Nombre del Servicio", 
                      direction: "ascending",
                    },
                  ],
                });
                const services = response.results.map(page => ({ 
                  title: page.properties["Nombre del Servicio"].title[0].plain_text, 
                  description: page.properties.Descripción.rich_text[0].plain_text, 
                  // Añade más propiedades según la estructura de tu tabla de Notion
                }));
                require("fs").writeFileSync("_data/services.json", JSON.stringify(services, null, 2));
                console.log("services.json generated successfully.");
              } catch (error) {
                console.error("Error fetching Notion data:", error);
                // Escribir un array vacío para prevenir fallos en el despliegue
                require("fs").writeFileSync("_data/services.json", JSON.stringify([], null, 2));
                console.log("Generated empty services.json due to error.");
              }
            }
            fetchServices();
          '
      - name: Upload _data directory
        uses: actions/upload-artifact@v4
        with:
          name: notion-data
          path: _data

  build:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Notion data
        uses: actions/download-artifact@v4
        with:
          name: notion-data
          path: _data

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: . # Tu sitio de Jekyll está en la raíz
          destination: _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
